# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc15c23edcca29d38a419177862f0e7d6ac5cd4738355a5e5d60882b763e0de7d6706eae0b7c63da26e61684f856a719137908b2c7f28c3b4816e65d21bade2

test:
  secret_key_base: 6bc49e07cd52355182441d5edfb90416e523ff9061c4bd77651b0bbed1112d738fed52b8115e6a508814ecfe30da98c46659d7117d5dbac25df44ae7885384f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
